apiVersion: v1
entries:
  nats:
  - apiVersion: v2
    appVersion: 2.6.3
    created: "2021-11-26T16:40:14.4502075+05:30"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 424df0f8cf2f0bbc6f4d6b2da645b1542c07230118043b0dc4aaa0fb5bebeaa0
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: wally@nats.io
      name: Waldemar Quevedo
      url: https://github.com/wallyqs
    - email: colin@nats.io
      name: Colin Sullivan
      url: https://github.com/ColinSullivan1
    - email: jaime@nats.io
      name: Jaime Piña
      url: https://github.com/variadico
    name: nats
    urls:
    - https://pinumallanaveen.github.io/Helm/nats-0.9.2.tgz
    version: 0.9.2
generated: "2021-11-26T16:40:14.4405131+05:30"
